# Generated by Django 3.1.1 on 2020-10-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_abtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartd',
            name='oldpeak',
            field=models.FloatField(),
        ),
    ]
