# Generated by Django 3.1.1 on 2021-04-11 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20201101_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='physical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(79), django.core.validators.MinValueValidator(0)])),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('trans', 'trans')], max_length=15)),
                ('self_employed', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=15)),
                ('family_history', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=15)),
                ('treatment', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=15)),
                ('work_interfere', models.CharField(choices=[("Don't know", "Don't know"), ('Never', 'Never'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Sometimes', 'Sometimes')], max_length=15)),
                ('no_employees', models.CharField(choices=[('1-5', '1-5'), ('6-25', '6-25'), ('26-100', '26-100'), ('100-500', '100-500'), ('500-1000', '500-1000'), ('More than 1000', 'More than 1000')], max_length=20)),
                ('remote_work', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=15)),
                ('tech_company', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=15)),
                ('benefits', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ("Don't know", "Don't know")], max_length=15)),
                ('care_options', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Not sure', 'Not sure')], max_length=15)),
                ('wellness_program', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ("Don't know", "Don't know")], max_length=15)),
                ('seek_help', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ("Don't know", "Don't know")], max_length=15)),
                ('anonymity', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ("Don't know", "Don't know")], max_length=15)),
                ('leave', models.CharField(choices=[("Don't know", "Don't know"), ('Somewhat difficult', 'Somewhat difficult'), ('Somewhat easy', 'Somewhat easy'), ('Very difficult', 'Very difficult'), ('Very easy', 'Very easy')], max_length=20)),
                ('mental_health_consequence', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Maybe', 'Maybe')], max_length=15)),
                ('phys_health_consequence', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Maybe', 'Maybe')], max_length=15)),
                ('coworkers', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Some of them', 'Some of them')], max_length=15)),
                ('supervisor', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Some of them', 'Some of them')], max_length=15)),
                ('mental_health_interview', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Maybe', 'Maybe')], max_length=15)),
                ('phys_health_interview', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Maybe', 'Maybe')], max_length=15)),
                ('mental_vs_physical', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ("Don't know", "Don't know")], max_length=15)),
                ('obs_consequence', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=15)),
                ('age_range', models.CharField(choices=[('0-20', '0-20'), ('21-30', '21-30'), ('31-65', '31-65'), ('66-100', '66-100')], max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='heartd',
        ),
    ]
