
version: "3.9"
services:
#  db:
#    image: postgres
#    environment:
#      - POSTGRES_DB=coursework
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=258852
#      - POSTGRES_HOST_AUTH_METHOD=trust
#    ports:
#      - "5432:5432"
#    volumes:
#      - data:/var/lib/postgresql/data
  web:
    build: .
    command:  bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/web_django
    environment:
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    ports:
      - "8000:8000"

#volumes:
#  data:



