# Generated by Django 3.1.1 on 2020-10-18 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20201013_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartd',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='heartd',
            name='ca',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='heartd',
            name='cp',
            field=models.IntegerField(choices=[(1, 'Typical angina'), (2, 'Atypical angina'), (3, 'Non-anginal pain'), (4, 'Asymptomatic')]),
        ),
        migrations.AlterField(
            model_name='heartd',
            name='exang',
            field=models.IntegerField(choices=[(1, True), (0, False)]),
        ),
        migrations.AlterField(
            model_name='heartd',
            name='fbs',
            field=models.IntegerField(choices=[(1, True), (0, False)]),
        ),
        migrations.AlterField(
            model_name='heartd',
            name='oldpeak',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='heartd',
            name='restecg',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Having ST-T wave abnormality'), (2, 'Hypertrophy')]),
        ),
        migrations.AlterField(
            model_name='heartd',
            name='thalach',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='heartd',
            name='trestbps',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
