# Generated by Django 3.1.1 on 2020-10-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20201021_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartd',
            name='chol',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='heartd',
            name='fbs',
            field=models.IntegerField(choices=[(1, 'Lower than 120mg/ml'), (0, 'Greater than 120mg/ml')]),
        ),
        migrations.AlterField(
            model_name='heartd',
            name='slope',
            field=models.IntegerField(choices=[(1, 'upsloping'), (2, 'flat'), (3, 'downsloping')]),
        ),
        migrations.AlterField(
            model_name='heartd',
            name='thal',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Fixed defect'), (3, 'Reversable defect'), (4, 'Nan')]),
        ),
    ]
