# Generated by Django 3.1.1 on 2020-11-01 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20201030_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartd',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(79), django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='heartd',
            name='chol',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(570), django.core.validators.MinValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='heartd',
            name='oldpeak',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.3)]),
        ),
        migrations.AlterField(
            model_name='heartd',
            name='thalach',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(230), django.core.validators.MinValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='heartd',
            name='trestbps',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(90)]),
        ),
    ]
